### ISSUE TITLE
PDF workaround scaling not working

### ISSUE THREAD

**Issue by theclue** [lifelike/countersheetsextension#21]
Unfortunately the PDF workaround doesn't seem to work yet.

Execuiting the master branch in command line (I'm using Travis-CI for continuos deployment) all the generated PDF are identical and showing only the uppermost layer.

Since they are huge in size, I suspect the all the layers are stacked on each file.

**Comment by lifelike** [comment]
Noted. Too bad. I just saw this and will have a look at it when I find some time.

**Comment by theclue** [comment]
tnx allot! this is really impacting, as I'm not able to use the up-to-date master branch version of the script in my production environment :/

**Comment by lifelike** [comment]
The countersheet.py in your repo is different from my latest version, but I guess you tested with the latest version just did not commit it since it did not fix the issue? I will have a look once I have managed to script build all your decks properly locally. A bit short on time for this unfortunately at the moment.

**Comment by theclue** [comment]
exactly. I had to use a previous commit since the master one has the stacked layers bug, so for continuing the development I had to revert to a previous commit version (this is the commit key for the file I'm using: 6845bda4c0cdfc887a1d82a02f00755ab241590c)

**Comment by lifelike** [comment]
Bug fixed. It was a stupid thing with setting the style on layers to be hidden that was broken when the layer did not have a display style set already. This might have been an unknown issue for a long time with how styles are replaced in general when creating sheets, because the same function was used.
