### ISSUE TITLE
Back Counters misaligned

### ISSUE THREAD

**Issue by theclue** [lifelike/countersheetsextension#22]
When trying to create a two side counters, I see that the counters on the back are misaligned vs the ones on the front. As facts, the one on the back are centered in page, while the one on the front are placed on the left-upper corner of the page.

In addition, the cutting guides are rendered only on the front pages.

**Comment by lifelike** [comment]
The cuttings guides are only on one side by design. I have thought of adding options to be able to put them on either or both sides, but currently they are only on the front.

Never put any thought in aligning the front and back, because I always assumed they would be printed separately anyway. But in case someone is actually planning on printing them dual-sided on the same sheet of paper I guess it is a good idea to move the back layer to match the position of the front layer. I will look into that.

**Comment by lifelike** [comment]
I looked at the test-cases I have that are two-sided (in svgtests/expected) and they look like they are aligned to me. More information or example needed to do anything about this.

**Comment by theclue** [comment]
tried on a brand-new file made from scratch: they are aligned.

thus, (most probably) the bug was due to a corrupt svg file from my side
