### ISSUE TITLE
Missing image links in SVG file

### ISSUE THREAD

**Issue by theclue** [lifelike/countersheetsextension#24]
Since PDF output is not working atm due to existing bugs (stacked layers, shrunk in size etc.), I'm switching to SVG output, but image links are broken. It seems it's looking to the wrong paths.

These files would explain better what I mean [here](https://9thcirclegames.github.io/wisdom-of-cthulhu/)
(strange enough the "deck" files work perfectly, while the "great old ones" suffer these strange behaviours)

These bugs are delaying the prototyping of my game and I'm terribly worried about that. I would really be glad to help you in the fixing but I don't know python. But if you need further testing or help of any kind, I'll be happy to help.

**Comment by lifelike** [comment]
File links in the file I looked in looked ok, but the image files could not be accessed (error 403 forbidden from the web server). Both files were missing images, not only the great old ones. Perhaps the deck file worked when you looked at it locally? The images must remain in the same directory (or same relative directory if you give paths including directory names) at all times because images are not inlined (you can manually use one of the bundled effects in Inkscape to inline images, but the resulting SVG will be huge).

There might of course be some other problem as well, but that looks like the most obvious one.

I will set things up so I can test all your decks locally to see what I can do about the various errors you reported.

**Comment by theclue** [comment]
got it! This because images in the output SVG are linked, not embedded. I didn't noticed itat first.

good to know, tnx allot!
