### ISSUE TITLE
cs_layout rectangle counters alignment

### ISSUE THREAD

**Issue by ernierasta** [lifelike/countersheetsextension#66]
Hi Pelle!
Do you think it would be possible to allow user to configure how counters (components) are arranged inside cs_layout rectangle?

Currently they are aligned to the top right corner of the box (I am not talking about order, only alignment), which is logical.

I am creating gutter fold layout. I am not using BACK functionality, just two rectangles in cs_layout and line between them. Problem is, that I have to be sure that distance between fronts <--> center line and backs <--> center line is exactly the same. Solution would be to tell upper box to align components from bottom left corner.

I am not sure how difficult it would be to implement or how it should work. Maybe we could use some defined names to set alignment, something like `myname_bottomleft`?

Of course I can workaround it by calculating rectangle to exactly fit components, but it would require to re-adjust for different counter sizes.

**Comment by lifelike** [comment]
Making the boxes exactly the correct size sounds like a good workaround (I usually do that anyway). I agree this sounds useful though, but it sounds like you would want this per box, so probably would require some trick like using the id of each layout box for this, unless there is some existing SVG attribute that could be used for this.

**Comment by ernierasta** [comment]
Ignore this for now, in few days I will make some PR's. I think it is quite trivial to add automatic gutter fold layout generation. It would allow user to use the same csv for duplex layout and gutter fold, so it would be most elegant solution IMO. We could use BACK row for both layouts. I would like to add checkbox named gutter fold and settings for fold line distance. I think it will be just few lines of code added. Do you think that it would be acceptable?

**Comment by lifelike** [comment]
What does it add beyond what is already possible, since adding the options for rotating fronts and backs? There is an example prototype_cards_two_sided.csv for use with prototype_cards.svg. Maybe the problem is that there is no real documentation explaining that (and that you need to manually set what rotation to apply to front and back, like -90 and +90 for instance, combined with the option to print both fronts and backs on the same side)?

Maybe one thing that is lacking is a way to automatically include a fold line. I do not remember if there is a way to get that. I might have manually added that to a cs_background layer. It would of course be nice to automatically generate that (maybe always do that when using the option to put both sides on the same page?).

A bit of documentation for this would be useful as well. It looks like the only place this is described is in the bgg thread in this post:
https://www.boardgamegeek.com/thread/299033/article/34099067#34099067

Or is there anything more to a gutter fold layout I am overlooking? It is not anything I have used myself.

**Comment by ernierasta** [comment]
Thank you for quick response!

Hehe :-D, that is great! I did not found mentioned example (I have completely ignored **template** directory ). Well I was somehow fixed on landscape page, so code changes seems necessary, but your example works great.

Main problem with it is related to distance between component and its back (from component to folding line and from folding line to back). You can see this in your your example - backs cutting lines are too close to page border(they ends 2.6mm from page right border). It would be great if we could configure distance from folding line. 

Auto-generating folding line would be very nice (it could be styled the same way as cutting marks are, f.e: cs_foldstyle), especially combined with customizable distance from folding line. This would also simplify generating duplex and gutter fold from the same file.

Also configurable layer name (or layer name suffix) would be great. I am going to propose your smart [solution for multiple configuration](/lifelike/countersheetsextension/wiki/Multiple-Configurations) in tutorial. And it would be great if we could generate multiple layouts from the same svg without the need of deleting previously generated ones.

I am way offtopic on this issue. ;-) But generally I would like to achieve effect, when one can generate pdf's for 2 layouts in few clicks and I am close to that.

**Comment by lifelike** [comment]
Yes, as you found out, the distance is given by the cs_layout box. I think that is the only possible way really, because the front and back have to line up when you fold, so moving the box closer or further away from the fold will move the back the same distance in the opposite direction. I do not really think there is anything about that to configure, it just has to be that way.

I would be happy to accept an update to add an optional fold line.

The suffix for different layouts is definitely planned, but no idea when. A pull request would be likely to be accepted.

In general any improvements that are not breaking anything or likely to make the code in even worse shape for future updates are very welcome. Something like allowing fronts and backs to be positioned in a landscape page with a horizontal fold could work (not sure if it is THAT important, since you can just rotate everything like in my example?) but it would have to be done with some consideration of not forcing a lot of special cases into the code. The reason it was done the way it is now is that it was possible without really breaking any old logic, so it is likely to work well even if more features are added. If the backs are placed below a horizontal fold line they have to be ordered in a new way compared to all other layouts, and I fear that that might result in kludges all over the code to handle properly, unless there is a clever way to abstract that out.

**Comment by ernierasta** [comment]
I am planning to solve my issues. ;-) First two PRs landed.

I will definitely send PR for layout suffix-es soon.

That landscape idea was more self-criticsm then proposal (I have code to do that, but I will not create PR for that - I do not think it is usefull). ;-) I completely understand what you are saying - feature creep is not good to have. BTW: while structure of you python file may be not perfect, after so long development - it is great! No problem to move around and understand what is probably going on.
I will see later if centering on page makes any problems in practice, if so, we can try to figure out some sensible solution (brainstorm: maybe just allow user to configure "fronts" horizontal/vertical offset like there is now for backs).
