### ISSUE TITLE
Shouldn't Referencing a New Template in CSV File Create a New Page/Layer?

### ISSUE THREAD

**Issue by jlr1001** [lifelike/countersheetsextension#83]
Thanks for all the work you've put into Countersheet I'm finding it quite versatile.

I'm using it to layout a card game, so my cs_layout layer is basically a 3x3 card grid. This is create for most of the entries in my csv file, however I have some specialized cards whose amounts aren't divisible by 9. So when I create my countersheet layers I end up with a layer of, say, 8 cards where the 9th box has the first entry from the next set of cards (template) in my csv file.

I've been trying to figure out how to have CS skip that empty 9th entry and start the next layer with the next template set. At first ENDBOX/ENDROW sounded promising until I hit this wall, "When there is no cs_layout ENDBOX will end the current page instead." I need to use cs_layout to position my cards correctly for cutting out prototypes, but this is the exact behavior I want except when using cs_layout....

In the absence of creating a new "null" entry like ENDBOX, it makes sense to me that when I reference a new main template--not a template I'm referencing with * or +--then CS should treat that as the start of a new page/layer. That way the cards with amounts divisible by 9 would print fine, and for templates where I only have 7 entries in my csv file the unused boxes would just remain empty on the rendered layer/page.

Am I missing something obvious? Is this easily doable?

Thanks again!

**Comment by jzedwards** [comment]
I’d just build it into the CSV; it sounds like you have 9 layout boxes, rather than one box of 9

 

If you have 1 box that allows up to 9 cards, endbox should work, I think…

 

From: jlr1001 ***@***.***> 
Sent: 28 January 2022 15:53
To: lifelike/countersheetsextension ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lifelike/countersheetsextension] Shouldn't Referencing a New Template in CSV File Create a New Page/Layer? (Issue #83)

 

Thanks for all the work you've put into Countersheet I'm finding it quite versatile.

I'm using it to layout a card game, so my cs_layout layer is basically a 3x3 card grid. This is create for most of the entries in my csv file, however I have some specialized cards whose amounts aren't divisible by 9. So when I create my countersheet layers I end up with a layer of, say, 8 cards where the 9th box has the first entry from the next set of cards (template) in my csv file.

I've been trying to figure out how to have CS skip that empty 9th entry and start the next layer with the next template set. At first ENDBOX/ENDROW sounded promising until I hit this wall, "When there is no cs_layout ENDBOX will end the current page instead." I need to use cs_layout to position my cards correctly for cutting out prototypes, but this is the exact behavior I want except when using cs_layout....

In the absence of creating a new "null" entry like ENDBOX, it makes sense to me that when I reference a new main template--not a template I'm referencing with * or +--then CS should treat that as the start of a new page/layer. That way the cards with amounts divisible by 9 would print fine, and for templates where I only have 7 entries in my csv file the unused boxes would just remain empty on the rendered layer/page.

Am I missing something obvious? Is this easily doable?

Thanks again!

**Comment by jlr1001** [comment]
> I’d just build it into the CSV; it sounds like you have 9 layout boxes, rather than one box of 9 If you have 1 box that allows up to 9 cards, endbox should work, I think… 

Building it into the CSV, i.e. blank cells as filler, could work I guess. I have one cs_layout layer that has nine rectangles arranged in a grid. Is this 9 layout boxes or one box of 9? I don't know. Either way, ENDBOX doesn't work the way I'm expecting.

**Comment by jzedwards** [comment]
You create a boxes on CS_LAYOUT and that will fit as many items as it can into each box

 

If you create 9 separate boxes, each for 1 card, ENDBOX will do nothing – your cs_layout should be one box, not 9

If you create ONE big box that will take 9 cards, and enter only 4 then do ENDBOX, it will fill 4, then go to next sheet

**Comment by lifelike** [comment]
I think [jzedwards](https://github.com/jzedwards) is correct. You need to draw one big rectangle for the area where you want the cards to be (or just not have a cs_layout layer at all if the default is good enough; it will fill an area as big as possible in the center of the page with enough room for the added cutting lines around).
