### ISSUE TITLE
running "apply" multiple times overlays existing output

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/countersheetsextension#9]
If you run "apply" to create counters, then increase the registration marks length and run it again, the old counters are still present. This is true even if you don't change the registration marks length, but changing that makes it obvious that this is happening.

**Comment by jrvjrv** [comment]
I see now that each time you click "apply" you get a new layer with the counters. This may be a documentation bug, but you should give some thought to using only one layer and clearing it each time before recreating the counters. I can't think of any good reason you might want multiple copies of the counters even in separate layers.

**Comment by lifelike** [comment]
I will look into it.

The idea is that if a counter exists already it is updated with the new values. I wanted to be able to re-arrange the counters (for an example-of-play) and then update the values without having to re-position them again every time there was an update). Perhaps that feature is a bit too obscure, and also broken if there was a new layer generated.

**Comment by lifelike** [comment]
A problem with clearing the old counters is that someone might have edited them for whatever reason. It would probably be better to always just create new layers with new sheets and ignore any existing counters, but then they have to be considered at least when generating id-attributes anyway, so there is a bit of complexity (and risk) involved in fixing this. But should probably remove that obscure feature of updating values in old sheets because it is more confusing than useful.

**Comment by lifelike** [comment]
Did two things to fix this (in most recent two commits):

1. Refuse to generate a sheet if a layer with same name exists. Finally a good reason to use the Name parameter in the effect dialog, because using that you can make it generate the new sheet anyway as the layer names will no longer collide.

2. Removed the obscure confusing thing about reusing old counters and updating them. But the old counter is still found to have its id changed, so that it is certain that the latest generated counter has the ID given in the csv (if any).
