### ISSUE TITLE
Counter sheet extension won't make counters

### ISSUE THREAD

**Issue by InevitablePuma5** [lifelike/countersheetsextension#96]
Hello all!
Keep getting this error message. This appears on both examples and stuff I try to generate. The only variation is in the last line where it will list KeyError:'first_column_name' with the quote containing the name of whatever the first column name is.
I'm not code savvy so any help is appreciated.

The current directory is invalid.
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\countersheet.py", line 2247, in <module>
    effect.run()
  File "C:\Program Files\WindowsApps\25415Inkscape.Inkscape_1.2.0.0_x64__9waqn51p1ttv2\VFS\ProgramFilesX64\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\countersheet.py", line 1528, in effect
    width, height=self.generatecounter(c, rects, layer,
  File "C:\Users\username\AppData\Roaming\inkscape\extensions\countersheet.py", line 823, in generatecounter
    x = self.geometry[rectname].x
KeyError: 'card'

**Comment by lifelike** [comment]
It is saying that there is no template called 'card' in the current document (SVG) you have open in Inkscape. The CSV data you load has to match what is in the current document. So if you are trying to generate the cards in prototype_cards_all.csv you have to have prototype_cards.svg open in Inkscape for instance.

That is my guess, but it could be something else.

**Comment by InevitablePuma5** [comment]
Unfortunately that's exactly the example I was messing with. I have prototype_cards.svg open and I'm loading prototype_cards_all.csv with the extension. Unfortunately, no ammount of tinkering seems to make it go away. I downloaded my copy of inkscape from the microsoft store. I wonder it that's the issue.

**Comment by jppcurran** [comment]
Any progress on this? I am using Inkscape 1.3, and am getting the same kind of error message when I try to walk through "Your First Countersheet" on the wiki.  In that case, the error sequence is 
Terminate called after throwing an instance of 'Gio::Error'
Traceback (most recent call last):
  File "C:\Users\jcurran3\AppData\Roaming\inkscape\extensions\countersheet.py", line 2617, in <module>
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Users\jcurran3\AppData\Roaming\inkscape\extensions\countersheet.py", line 1811, in effect
    width, height = self.generatecounter(
  File "C:\Users\jcurran3\AppData\Roaming\inkscape\extensions\countersheet.py", line 1010, in generatecounter
    x = self.geometry[rectname].x
KeyError: 'unit'

"Unit" does appear as an attribute in counters.svg...

**Comment by vrhee** [comment]
(There's a separate related discussion going on elsewhere, but I'm going to capture it here as well for posterity...)

I spent a few minutes on this, and one thing I noticed (at least with Inkscape 1.3/Windows) is that when I run 'inkscape --query-all <filename>' from the command line, I get no output. Which means the queryAll() method in line 1192 of countersheet.py is borked, as the line parsing for the object geometry outputs nothing.

Through a bunch of logwrite() calls, it appears everything is fine until the call to popen3() in line 1204. So I decided to hack together a quick test, replacing lines 1203-1204:

        cmd = 'inkscape --query-all "%s"' % tmpfile[1]
        out, err = popen3(cmd)

with

        out = inkex.command.inkscape(tmpfile[1], "--query-all")

But since inkex.command.inkscape() lacks a stderr output, I also had to comment out line 1220:

        print_filtered_stderr(err)

But it appears to work. Except for the loss of stderr, of course. But it's something, I guess, as it seems to work for my existing templates I've tested it out on.

And for what it's worth, this "fix" appears to still work with Inkscape 1.2 as well. Again, this is all being tested solely with the Windows 64-bit release builds.

**Comment by lifelike** [comment]
I will tag a new release (3.1) if it looks like this works in Inkscape 1.3 on Windows now. It looks like everything is still working fine with Inkscape 1.1.1 on Linux. Had to do some other minor changes to the code to fix the other place where inkscape was called using popen3 (assuming that was also broken, but even if it was not it looks as if inkex.command is the recommended way to do it).
